version: '3'

services:
  web:
    build: .
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      # One per each custom theme.
      # Example:
      # - ./themes/custom/causascomunes:/opt/jboss/keycloak/themes/causascomunes
      - ./themes/custom/causascomunes:/opt/jboss/keycloak/themes/causascomunes
    networks:
      - keycloak_network
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge  